version: '3.8'

services:
  api:
    image: nestjs-docker
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.dev
