version: '3.8'

services:
  api:
    image: nestjs-docker
    container_name: api-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: dbProject
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=projects
      - POSTGRES_USER=daker
      - POSTGRES_PASSWORD=secret
